---
title: "p8131_hw2_jsg2145"
author: "Jared Garfinkel"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
# Create a dataframe

dos_df <- tibble(
  dose = c(0:4),
  dead = c(2, 8, 15, 23, 27),
  alive = 30 - dead
)
```

```{r}
dos_logit <- dos_df %>% 
  glm(data = ., cbind(dead, alive) ~ dose, family = binomial(link = "logit"))

summary(dos_logit)
```

```{r}
dos_probit <- dos_df %>% 
  glm(data = ., cbind(dead, alive) ~ dose, family = binomial(link = "probit"))

summary(dos_probit)
```

```{r}
dos_cloglog <- dos_df %>% 
  glm(data = ., cbind(dead, alive) ~ dose, family = binomial(link = "cloglog"))

summary(dos_cloglog)
```
```{r}
dos_logit_ci = dos_logit %>% 
  broom::tidy() %>% 
  mutate(
    lower = round((estimate - qnorm(.975) * std.error), digits = 2),
    upper = round((estimate + qnorm(.975) * std.error), digits = 2)) %>%
  select(term, estimate, lower, upper) %>% 
  filter(term == "dose") %>% 
  mutate(term = recode(term, dose = "logit"))

dos_probit_ci = dos_probit %>% 
  broom::tidy() %>% 
  mutate(
    lower = round((estimate - qnorm(.975) * std.error), digits = 2),
    upper = round((estimate + qnorm(.975) * std.error), digits = 2)) %>% 
  select(term, estimate, lower, upper) %>% 
  filter(term == "dose") %>% 
  mutate(term = recode(term, dose = "probit"))

dos_cloglog_ci = dos_cloglog %>% 
  broom::tidy() %>% 
  mutate(
    lower = round((estimate - qnorm(.975) * std.error), digits = 2),
    upper = round((estimate + qnorm(.975) * std.error), digits = 2)) %>%
  select(term, estimate, lower, upper) %>% 
  filter(term == "dose") %>% 
  mutate(term = recode(term, dose = "cloglog"))

table = rbind(dos_logit_ci, dos_probit_ci, dos_cloglog_ci)
```

```{r}
dev_logit = round(deviance(dos_logit), digits = 2)

dev_probit = round(deviance(dos_probit), digits = 2)

dev_cloglog = round(deviance(dos_cloglog), digits = 2)

deviance = c(dev_logit, dev_probit, dev_cloglog)

table = table %>% 
  mutate(deviance = c(dev_logit, dev_probit, dev_cloglog))
```

```{r}
p_logit = predict(dos_logit, data.frame(dose=.01), se.fit=TRUE, type='response')

p_probit = predict(dos_probit, data.frame(dose=.01), se.fit=TRUE, type='response')

p_cloglog = predict(dos_cloglog, data.frame(dose=.01), se.fit=TRUE, type='response')

table = table %>% 
  mutate(p_estimate = c(round(p_logit[[1]], digits = 2), round(p_probit[[1]], digits = 2), round(p_cloglog[[1]], digits = 2))) %>% 
  knitr::kable()

table
```

## 1ii

```{r}
beta0_l=dos_logit$coefficients[1]
beta1_l=dos_logit$coefficients[2]
betacov_l=vcov(dos_logit)
x0fit_l=-beta0_l/beta1_l
exp(x0fit_l)

varx0_l=betacov_l[1,1]/(beta1_l^2)+betacov_l[2,2]*(beta0_l^2)/(beta1_l^4)-2*betacov_l[1,2]*beta0_l/(beta1_l^3)
c(x0fit_l,sqrt(varx0_l)) # point est and se
exp(x0fit_l+c(qnorm(0.05),-qnorm(0.05))*sqrt(varx0_l))

beta0_p=dos_probit$coefficients[1]
beta1_p=dos_probit$coefficients[2]
betacov_p=vcov(dos_probit)
x0fit_p=-beta0_p/beta1_p
exp(x0fit_p)

varx0_p=betacov_p[1,1]/(beta1_p^2)+betacov_p[2,2]*(beta0_p^2)/(beta1_p^4)-2*betacov_p[1,2]*beta0_p/(beta1_p^3)
c(x0fit_p,sqrt(varx0_p)) # point est and se
exp(x0fit_p+c(qnorm(0.05),-qnorm(0.05))*sqrt(varx0_p))

beta0_c=dos_cloglog$coefficients[1]
beta1_c=dos_cloglog$coefficients[2]
betacov_c=vcov(dos_cloglog)
x0fit_c=(log(log(2))-beta0_c)/beta1_c
exp(x0fit_c)

varx0_c=betacov_c[1,1]/(beta1_c^2)+betacov_c[2,2]*(beta0_c^2)/(beta1_c^4)-2*betacov_c[1,2]*beta0_c/(beta1_c^3)
c(x0fit_c,sqrt(varx0_c)) # point est and se
exp(x0fit_c+c(qnorm(0.05),-qnorm(0.05))*sqrt(varx0_c))
```




